---
# tasks file for symfony2
- include: 00-facts.yml

- name: Create base deployment directories.
  file: state=directory path={{item.path}}
  with_items:
    - { path: "{{symfony_current_release_dir}}" }
    - { path: "{{symfony_shared_dir}}" }

- name: Create managed shared directories.
  file: state=directory path="{{symfony_shared_dir}}/{{item.path}}"
  with_items: "{{symfony_project_shared_folders}}"

- name: Deploy to remote servers
  synchronize: src={{symfony_project_deploy_from}} dest={{symfony_current_release_dir}} set_remote_user=yes recursive=yes delete=yes archive=yes compress=yes

- name: Ensure shared folders are absent in release.
  file: state=absent path="{{symfony_current_release_dir}}/{{item.path}}"
  with_items: "{{symfony_project_shared_folders}}"

- name: Ensure managed folders are present.
  file: state=directory path="{{symfony_current_release_dir}}/{{item.path}}"
  with_items: "{{symfony_project_managed_folders}}"

- name: Read composer.json
  shell: cat {{symfony_current_release_dir}}/composer.json
  register: composer_content

- name: Include post folder creation tasks.
  include: "{{symfony_project_post_folder_creation_tasks}}"
  when: symfony_project_post_folder_creation_tasks

- name: Create symlinks to shared directories.
  file: state=link src="{{symfony_shared_dir}}/{{item.src}}" path="{{symfony_current_release_dir}}/{{item.path}}"
  with_items: "{{symfony_project_shared_folders}}"

- include: 10-config.yml

- include: 20-composer.yml

- name: Include pre cache warmup tasks.
  include: "{{symfony_project_pre_cache_warmup_tasks}}"
  when: symfony_project_pre_cache_warmup_tasks

- include: 30-cache.yml

- include: 40-assets.yml

- include: 50-migrations.yml

- name: Create release file.
  copy: content="{{symfony_current_release}}" dest="{{symfony_current_release_dir}}/RELEASE" mode=644

- name: Include pre live switch tasks.
  include: "{{symfony_project_pre_live_switch_tasks}}"
  when: symfony_project_pre_live_switch_tasks

- name: Create symlink for release.
  file: state=link src="{{symfony_current_release_dir}}" path="{{symfony_project_root}}/current"

- name: Include post live switch tasks.
  include: "{{symfony_project_post_live_switch_tasks}}"
  when: symfony_project_post_live_switch_tasks

- include: 60-clean_releases.yml